name: Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: colinaaa/setup-riscv-gnu-toolchain@latest
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
